version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest-crud
    ports:
      - 5432:5432

  app:
    build: .
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest-crud
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    ports:
      - 3000:3000
